service:
  name: portfolio-tracker-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        # - arn:aws:dynamodb:us-west-2:380040197061:table/PortfolioTrackerTable
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/PortfolioTrackerTable

resources:
  Resources:
    PortfolioTrackerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PortfolioTrackerTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: ip
            AttributeType: S
        KeySchema:
          - AttributeName: ip
            KeyType: HASH

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          method: POST
          path: /createUser
# custom:
#   bundle:
#     linting: true
