service:
  name: portfolio-tracker-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    PORTFOLIO_TRACKER_TABLE_NAME: ${self:custom.PortfolioTrackerTable.name}
  iamRoleStatements:
    - ${file(iam/PortfolioTrackerTableIAM.yml):PortfolioTrackerTableIAM}

resources:
  Resources:
    PortfolioTrackerTable: ${file(resources/PortfolioTrackerTable.yml):PortfolioTrackerTable}

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          method: POST
          path: /createUser

  logDivTime:
    handler: src/handlers/logDivTime.handler
    events:
      - http:
          method: POST
          path: /logDivTime

custom:
  bundle:
    linting: false
  PortfolioTrackerTable:
    name: !Ref PortfolioTrackerTable
    arn: !GetAtt PortfolioTrackerTable.Arn
