service:
  name: portfolio-tracker-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    PORTFOLIO_TRACKER_TABLE_NAME: ${self:custom.PortfolioTrackerTable.name}
  iamRoleStatements:
    - ${file(iam/PortfolioTrackerTableIAM.yml):PortfolioTrackerTableIAM}

resources:
  Resources:
    PortfolioTrackerTable: ${file(resources/PortfolioTrackerTable.yml):PortfolioTrackerTable}

functions:
  logUser:
    handler: src/handlers/logUser.handler
    events:
      - http:
          method: POST
          path: /logUser
          cors: true
    memorySize: 256

  logSession:
    handler: src/handlers/logSession.handler
    events:
      - http:
          method: POST
          path: /logSession
          cors: true
    memorySize: 256

  logDiv:
    handler: src/handlers/logDiv.handler
    events:
      - http:
          method: PATCH
          path: /logDiv
          cors: true

  logLink:
    handler: src/handlers/logLink.handler
    events:
      - http:
          method: PATCH
          path: /logLink
          cors: true

  getUser:
    handler: src/handlers/getUser.handler
    events:
      - http:
          method: GET
          path: /user
          cors: true

  getUserByIP:
    handler: src/handlers/getUserByIP.handler
    events:
      - http:
          method: GET
          path: /user/{ip}
          cors: true

custom:
  bundle:
    linting: false
  PortfolioTrackerTable:
    name: !Ref PortfolioTrackerTable
    arn: !GetAtt PortfolioTrackerTable.Arn
