service:
  name: tracker-service

frameworkVersion: "2"

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-west-2

functions:
  hello:
    handler: src/handlers/hello.handler
