PortfolioTrackerTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: PortfolioTrackerTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: ip
        AttributeType: S
    KeySchema:
      - AttributeName: ip
        KeyType: HASH
